version: '3.7'

services:

  server:
    image: backend
    container_name: 'cloud-storage-backend'
    build: ./
    ports:
      - "5500:5500"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/netology
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_LIQUIBASE_URL: jdbc:mysql://database:3306/netology
      SPRING_LIQUIBASE_USER: root
      SPRING_LIQUIBASE_PASSWORD: root

  database:
    image: mysql
    container_name: 'mysqlData'
    volumes:
      - /mysqlData:/var/lib/mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: netology
    ports:
      - "3306:3306"